### ISSUE TITLE
Retaliscratch 'Broken Pipe'?

### ISSUE THREAD

**Issue by MistaSee** [cognitivegears/retaliscratch#1]
Hi, thanks for the code.

I'm a teacher in Cambridge, and I've been trying to get this running for a 'wow' project to show my students. I've been playing around with the scratch interface for the DCThunder, and had it working until the shell reported a crash.

 The first time I tried to fire the rocket, retaliscratch.py dropped out and gives a Broken Pipe error message. 

pi@raspberrypi ~ $ sudo python retaliscratch.py
Traceback (most recent call last):
  File "retaliscratch.py", line 155, in <module>
    run_command(matchObj.group(1), int(matchObj.group(2)) if matchObj.group(2) != None else 0)
  File "retaliscratch.py", line 101, in run_command
    send_move(LEFT, value)
  File "retaliscratch.py", line 91, in send_move
    send_cmd(cmd)
  File "retaliscratch.py", line 87, in send_cmd
    DEVICE.ctrl_transfer(0x21, 0x09, 0, 0, [0x02, cmd, 0x00,0x00,0x00,0x00,0x00,0x00])
  File "/usr/local/lib/python2.7/dist-packages/usb/core.py", line 764, in ctrl_transfer
    self.__get_timeout(timeout))
  File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb0.py", line 522, in ctrl_transfer
    timeout
  File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb0.py", line 380, in _check
    raise USBError(errmsg, ret)
usb.core.USBError: [Errno None] error sending control message: Broken pipe

Any idea what that means? What is it that 's timing out? I updated all my python libraries, but no luck. When I disconnect and reconnect, it will run again for a short time but not very long.

Sorry, I'm really new to python.

Mark.

**Comment by MistaSee** [comment]
Actually, scratch that. 

Did some googling, and managed to work out that libusb0 is the old version. Updated to libusb 1.0.0 and now it's all fine! Learning every day.

Thanks again!

Mark.
